# Nome descritivo do workflow
name: Atualizar OMIE Dados Atuais Automaticamente

on:
  # Agenda a execução automática
  schedule:
    # === GRUPO 1: Manhã (Todos os dias) ===
    # Horário VERÃO (WEST=UTC+1) -> 11:40, 11:55, 12:10 (Local)
    - cron: '40 10 * * *'
    - cron: '55 10 * * *'
    - cron: '10 11 * * *'
    # Horário INVERNO (WET=UTC+0) -> 11:40, 11:55, 12:10 (Local)
    - cron: '40 11 * * *'
    - cron: '55 11 * * *'
    - cron: '10 12 * * *'

    # === GRUPO 2: Tarde (Seg-Sex) ===
    # Horário VERÃO (WEST=UTC+1) -> 18:00, 18:15, 18:30 (Local)
    - cron: '00 17 * * 1-5'
    - cron: '15 17 * * 1-5'
    - cron: '30 17 * * 1-5'
    # Horário INVERNO (WET=UTC+0) -> 18:00, 18:15, 18:30 (Local)
    - cron: '00 18 * * 1-5'
    - cron: '15 18 * * 1-5'
    - cron: '30 18 * * 1-5'
    
  # Permite execução manual
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para fazer commit

    steps:
      # 1. Checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # 2. Configura Python
      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Instala dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openpyxl numpy

      # 4. Executa o seu script Python
      - name: Executar o script omie_dados_atuais.py
        run: python scripts/omie_dados_atuais.py

      # 5. Verifica se o ficheiro de dados foi alterado e faz o commit/push
      - name: Fazer commit e push das alterações
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # A mensagem que aparecerá no histórico de commits
          commit_message: "BOT: Atualização automática do omie_dados_atuais.csv"
          
          # O ficheiro específico a ser verificado e adicionado
          file_pattern: data/omie_dados_atuais.csv
